[workspace]
members = [
    "crates/interprex",
    "crates/interprex-bucket",
    "crates/interprex-github",
    "crates/interprex-test",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/civitas-forge/interprex"
rust-version = "1.88"
version = "1.2.0"

[workspace.dependencies]
async-trait = "0.1.89"
base64 = "0.22.1"
bytes = "1.10.1"
chrono = { version = "0.4.41", features = ["serde"] }
crypto_box = { version = "0.9.1", features = ["seal"] }
fs2 = "0.4.3"
futures-util = "0.3.31"
http = "1.5.0"
http-body = "1.0.1"
http-body-util = "0.1.5"
jsonwebtoken = "10.1.0"
object_store = { version = "0.12.4", features = ["gcp"] }
octocrab = { version = "0.49.7", features = ["retry", "stream"] }
percent-encoding = "2.3.2"
secrecy = "0.10.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
toml = "0.9.8"
