[package]
name = "postel-contracts"
description = "Provider-neutral development-platform domain contracts"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
postel-model = { path = "../postel-model" }
secrecy.workspace = true
thiserror.workspace = true

[lib]
path = "src/lib.rs"
